import pygame
import chess
import chess.svg
import random

def print_board(board):
    print(board)

def draw_grid(screen):
    for x in range(0, 400, 50):
        pygame.draw.line(screen, (0, 0, 0), (x, 0), (x, 400))
        pygame.draw.line(screen, (0, 0, 0), (0, x), (400, x))

def get_computer_move(board):
    legal_moves = list(board.legal_moves)
    return random.choice(legal_moves)

def play_chess():
    pygame.init()
    screen = pygame.display.set_mode((400, 400))
    pygame.display.set_caption("Chess Game")

    board = chess.Board()
    while not board.is_game_over():
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return

        screen.fill((255, 255, 255))
        draw_grid(screen)

        for square, piece in board.piece_map().items():
            x = chess.square_file(square) * 50
            y = (7 - chess.square_rank(square)) * 50
            pygame.draw.rect(screen, (0, 0, 0), (x, y, 50, 50))
            # Draw chess pieces here

        pygame.display.flip()

        if not board.turn:  # Computer's turn (black)
            move = get_computer_move(board)
            try:
                board.push(move)
            except ValueError:
                print("Invalid move generated by computer player")

    pygame.quit()

if __name__ == "__main__":
    print("Welcome to Python Chess!")
    play_chess()
