import pygame
import chess
import chess.svg
import random

# Define a dictionary to map piece notation to image filenames
piece_image_filenames = {
    'r': 'black_rook.png',
    'n': 'black_knight.png',
    'b': 'black_bishop.png',
    'q': 'black_queen.png',
    'k': 'black_king.png',
    'p': 'black_pawn.png',
    'R': 'white_rook.png',
    'N': 'white_knight.png',
    'B': 'white_bishop.png',
    'Q': 'white_queen.png',
    'K': 'white_king.png',
    'P': 'white_pawn.png',
}

def load_piece_images():
    piece_images = {}
    for piece, filename in piece_image_filenames.items():
        piece_images[piece] = pygame.image.load(f'chess_pieces/{filename}')
    return piece_images

def draw_chess_board(screen, piece_images, board):
    # Draw the chessboard grid
    for row in range(8):
        for col in range(8):
            color = (255, 255, 255) if (row + col) % 2 == 0 else (0, 0, 0)
            pygame.draw.rect(screen, color, (col * 50, row * 50, 50, 50))

    # Draw the chess pieces on the board
    for square, piece in board.piece_map().items():
        x = chess.square_file(square) * 50
        y = (7 - chess.square_rank(square)) * 50
        piece_image = piece_images[piece.symbol()]
        screen.blit(piece_image, (x, y))

def get_computer_move(board):
    legal_moves = list(board.legal_moves)
    return random.choice(legal_moves)

def play_chess():
    pygame.init()
    screen = pygame.display.set_mode((400, 400))
    pygame.display.set_caption("Chess Game")

    board = chess.Board()
    piece_images = load_piece_images()

    while not board.is_game_over():
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                return

        draw_chess_board(screen, piece_images, board)

        pygame.display.flip()

        if not board.turn:  # Computer's turn (black)
            move = get_computer_move(board)
            try:
                board.push(move)
            except ValueError:
                print("Invalid move generated by computer player")

    pygame.quit()

if __name__ == "__main__":
    print("Welcome to Python Chess!")
    play_chess()
